base_url = "https://mfrr.xyz"
title = "mfrr.xyz"
compile_sass = true
build_search_index = true
theme = "anemone"

[markdown]
highlight_code = true

[extra]
list_pages = true
header_nav = [
  { url = "/", name_en = "/home/" },
  { url = "https://bsky.app/profile/mufar94.bsky.social", name_en = "/blogs/" },
  { url = "https://www.flickr.com/photos/201413722@N03/albums/", name_en = "/photos/" },
]
twitter_card = true

favicon = "favicon.ico"
