base_url = "https://mfrr.xyz"
title = "mfrr.xyz"
compile_sass = true
build_search_index = true
theme = "anemone"

[markdown]
highlight_code = true

[extra]
list_pages = true

header_nav = [
  { url = "/", name_en = "/home/" },
  { url = "/posts", name_en = "/posts/" },
  { url = "/portfolio", name_en = "/portfolio/" },
  { url = "/links", name_en = "/links/" },
  { url = "/about", name_en = "/about/" },
]
twitter_card = true

favicon = "favicon.ico"
