base_url = "https://mfrr.xyz"
title = "mfrr.xyz"
compile_sass = true
build_search_index = true
theme = "anemone"

[markdown]
highlight_code = true

[extra]
list_pages = true
header_nav = [
  { url = "/", name_en = "/home/" },
  { url = "/blogs", name_en = "/blogs/" },
  { url = "/photos", name_en = "/photos/" },
  { url = "/about", name_en = "/about/" },
]
twitter_card = true